{
 "title": "Casa_Segura",
 "description": "Se muestra la informacion obtenida por los sensores registrados",
 "time": { "from": "2022-07-15T00:13:45.500Z", "to": "2022-07-24T11:19:57.500Z" },
 "panels": [
  {
   "title": "Información de sensores instalados",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Temperatura",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  valor\nFROM med3\nWHERE sensor = \"Sensor Temp\""
    }
   ]
  },
  {
   "title": "Gases de estufa",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  valor as \"gas (µg/m3)\"\nFROM med3\nWHERE\n  sensor = \"Sensor MQ135\"\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  valor\nFROM med3\nWHERE sensor = \"Sensor Humedad\""
    }
   ]
  },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  valor as \"CO2(ppm)\"\nFROM med3\nWHERE\n  sensor = \"Sensor MQ6\"\nORDER BY fecha"
    }
   ]
  },
  { "title": "Historial", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  valor as \"Temperatura (°C)\"\nFROM med3\nWHERE\n  sensor = \"Sensor Temp\"\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  valor as \"Humedad (%)\"\nFROM med3\nWHERE\n  sensor = \"Sensor Humedad\"\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  valor AS \"CO2(ppm)\"\nFROM med3\nWHERE\n  sensor = \"Sensor MQ6\"\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Gases de estufa",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  valor as \"Gases (µg/m3)\"\nFROM med3\nWHERE\n  sensor = \"Sensor MQ135\"\nORDER BY fecha"
    }
   ]
  }
 ]
}