services:
  mysql:
    image: mariadb:10.8
    expose:
      - 3306
    volumes:
      - D:\desarrollo\capstone\Servicios\dbdata:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ro0tP@ss
      MARIADB_DATABASE: db_casa_segura
    networks:
      casasegura:
        aliases:
          - mysql

  mosquitto:
    image: eclipse-mosquitto:2.0.14
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - D:\desarrollo\capstone\Servicios\mosquitto\datos:/mosquitto/data
      - D:\desarrollo\capstone\Servicios\mosquitto\registros:/mosquitto/log
    networks:
      casasegura:
        aliases:
          - mosquitto

  nodered:
    image: nodered/node-red:2.2.2-12
    ports:
      - 1880:1880
    volumes:
      - D:\desarrollo\capstone\Servicios\nodered\data:/data
    networks:
      casasegura:
        aliases:
          - nodered

  openhab:
    image: "openhab/openhab:3.3.0"
    restart: always
    network_mode: host
    ports:
      - 8080:8080
      - 5007:5007
      - 8101:8101
      - 8443:8443
    volumes:
      - D:\desarrollo\capstone\Servicios\openhab\addons:/openhab/addons
      - D:\desarrollo\capstone\Servicios\openhab\conf:/openhab/conf
      - D:\desarrollo\capstone\Servicios\openhab\userdata:/openhab/userdata
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=America/Mexico_City"
    networks:
      casasegura:
        aliases:
          - openhab

volumes:
  datos:
    driver: local
  registros:
    driver: local
  dbdata:
    driver: local
  localtime:
    driver: local
  timezone:
    driver: local
  addons:
    driver: local
  conf:
    driver: local
  userdata:
    driver: local
  data:
    driver: local
  
networks:
   casasegura: {}